app_users/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
app_name = 'app_users'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='app_users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout_view'),
]

myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
]

projectapi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('app_users/', include('app_users.urls'))
]

app_users/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.

app_users/views.py
from django.shortcuts import render
from django.contrib.auth import logout 
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))

myapp/views.py
from django.shortcuts import render
import requests
import json
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'myapp/index.html')


@login_required
def home(request):
    context = {}
    if request.method == 'POST':
        name = request.POST.get('name')
        response = requests.get('https://itunes.apple.com/search?entity=song&limit=1&term=' + name)
        o = response.json()
        tracks_info = []
        for result in o['results']:
            track_info = {
                'trackname':result['trackName'],
                'previewUrl':result.get('previewUrl','')
            }
            tracks_info.append(track_info)
        context = {'tracks_info': tracks_info}
    return render(request, 'myapp/home.html', context)

app_users/templates/app_users/login.html
{% extends 'myapp/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">


{% block content %}

<div class="div-login">
    <form action="{% url 'app_users:login' %}" method="post" class="form-login">
        {% csrf_token %}
        <div class="imagem">
            <img src="{% static 'img/OIP.png' %}" alt="logo-login">
        </div>
        
        {{ form.as_p }}
     
        
        <input type="submit" value="sign in" id="button-login">
        <input type="hidden" name="next" value="{% url 'myapp:home' %}">
    </form>
</div>


{% endblock content %}

myapp/templates/myapp/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    {% if user.is_authenticated %}
      <p>ola, {{ user.username }} </p>
      <p><a href="{% url 'app_users:logout_view' %}">logout</a></p>
   {% else %}
      <a href="{% url 'app_users:login' %}">login</a>
      

{% endif %}
    <a href="{% url 'myapp:index' %}"><h1>api itunes</h1></a>
    {% block content %}{% endblock content %}
  </body>
</html>

myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block title %}home{% endblock title %}

{% block content %}

<form action="{% url 'myapp:home' %}" method="post">  {# Assumindo uma view diferente para lidar com o formulário #}
  {% csrf_token %}
  <label for="name">Digite o nome do cantor</label>
  <br>
  <input class="form-control" id="name" type="text" placeholder="Nome" name="name" autocomplete="off">
  <input type="submit" value="pesquisar" id="submit">
</form>

<h1>Músicas:</h1>
<ul>
  {% for track_info in tracks_info %}
       <li>{{ track_info.trackName }}</li>
  <audio controls>
    <source src="{{ track_info.previewUrl }}" type="audio/mpeg">
  </audio>
  <br>
  Your browser does not support the audio tag.
  {% endfor %}
</ul>
{% endblock content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/script.js' %}"></script>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block title %}index{% endblock %}



{% block content %}
<h1>Esse sistema vai te ajudar a ouvir Músicas do itunes</h1>
<a href="{% url 'myapp:home' %}">Ouvir Músicas...</a>
{% endblock content %}